on :
  push:
     branches:
        - develop
name: deploy test website on push
jobs:
  web-play:
     name: deplay
     runs-on: ubunto-latest
     steps:
      - name: get latest code
        uses: actions/checkoutv2

      - name: sync files
        uses: samkirkland/FTP-deploy-action@4.0.0
        with:
          server: ${{  secrets.ftp_host }}
          username: ${{  secrets.ftp_user   }}
          password: ${{  secrets.ftp_password  }}
          server-dir: public_html/vanessa/